[metadata]
name    = "default"
author  = "comnet"

[global]
plan    = "go-libp2p-testground"
case    = "node"
builder = "docker:go"
runner  = "local:docker"

total_instances = 51

[[groups]]
id = "boot"
instances = { count = 1 }

[[groups]]
id = "worker"
instances = { count = 50 }