name = "libp2p"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[[testcases]]
name = "textfile"
instances = { min = 1, max = 11, default = 11 }

  [testcases.params]
  file = { type = "string", default = "../content/1KB.txt" }
  latency = { type = "int", default = 100 } # 100 millisecond
  bandwidth = { type = "int", default = 20 } # 1MB per second

[[testcases]]
name = "smallimage"
instances = { min = 4, max = 102, default = 102 }

  [testcases.params]
  textfile = { type = "string", default = "../content/1KB.txt" }
  imagefile = { type = "string", default = "../content/756KB.jpg" }
  better_latency = { type = "int", default = 10 } # 10 millisecond
  better_bandwidth = { type = "int", default = 22 } # 4MB per second
  latency = { type = "int", default = 100 }
  bandwidth = { type = "int", default = 20 }
  timer = { type = "int", default = 100 }