name = "libp2p"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[[testcases]]
name = "ten-text"
instances = { min = 1, max = 11, default = 11 }

  [testcases.params]
  file = { type = "string", default = "../content/1KB.txt" }
  latency = { type = "int", default = 100 } # 100 millisecond
  bandwidth = { type = "int", default = 20 } # 1MB per second

[[testcases]]
name = "fifty-smallimage"
instances = { min = 1, max = 51, default = 51 }

  [testcases.params]
  file = { type = "string", default = "../content/756KB.jpg" }
  latency = { type = "int", default = 100 } # 100 millisecond
  bandwidth = { type = "int", default = 20 } # 1MB per second

[[testcases]]
name = "hundred-bigimage"
instances = { min = 1, max = 101, default = 101 }

  [testcases.params]
  file = { type = "string", default = "../content/2MB.jpg" }
  latency = { type = "int", default = 100 } # 100 millisecond
  bandwidth = { type = "int", default = 20 } # 1MB per second