name = "libp2p"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[[testcases]]
name = "node"
instances = { min = 1, max = 51, default = 51 }

  [testcases.params]
  small = { type = "string", default = "../content/1KB.txt" }
  medium = { type = "string", default = "../content/756KB.jpg" }
  large = { type = "string", default = "../content/2MB.jpg" }
  num = { type = "int", default = 2 }
  feature = { type = "bool", default = false }