global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'comnet-libp2p'
    docker_sd_configs:
      - host: 'unix:///var/run/docker.sock'
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        action: keep
        regex: 'comnet-libp2p'
    metrics_path: /debug/metrics/prometheus
